# Generated by Django 4.2.14 on 2024-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocalfile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
