# Generated by Django 4.2.14 on 2024-10-23 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
