# Generated by Django 4.2.14 on 2024-10-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='token',
        ),
    ]
