# Generated by Django 4.2.14 on 2024-10-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobstatusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmissionconnection',
            name='user',
        ),
    ]
