# Generated by Django 4.2.14 on 2024-10-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_jobsubmissionconnection_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsubmissionconnection',
            name='protocol',
            field=models.CharField(choices=[('redis', 'REDIS'), ('amqp', 'AMQP')], max_length=255),
        ),
    ]
