# Generated by Django 4.2.14 on 2024-11-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblocalfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
