# Generated by Django 4.2.14 on 2024-11-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_joblocalfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatusupdate',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
