# Generated by Django 4.2.14 on 2024-11-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobstatusupdate_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatusupdate',
            name='info',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
