# Generated by Django 4.2.14 on 2024-12-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobstatusupdate_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatusupdate',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
