# Generated by Django 4.2.14 on 2025-01-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_jobstatusupdate_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
