exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [pre-commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  ## This plugin is no longer supported
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       args: ['--tab-width', '2', '--single-quote']
  #       exclude: 'spectrumx_visualization_platform/templates/'

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.22.1'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '4.2']

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-reformat-django
        exclude: 'frontend/'
      - id: djlint-django
        exclude: 'frontend/'

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.12.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  #       types: [file]
  #       additional_dependencies:
  #         - eslint-plugin-react@7.37.1
  #         # - eslint-plugin-react-hooks@5.0.0
  #         # - eslint-plugin-jsx-a11y@6.10.0
  #         # - eslint-plugin-import@2.31.0
  #         # - eslint-plugin-simple-import-sort@12.1.1

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
