volumes:
  spectrumx_visualization_platform_local_postgres_data: {}
  spectrumx_visualization_platform_local_postgres_data_backups: {}
  spectrumx_visualization_platform_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: spectrumx_visualization_platform_local_django
    # container_name: spectrumx_visualization_platform_local_django
    depends_on:
      - postgres
      # - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      - spectrumx_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/local/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - django
      - nginx
    networks:
      - spectrumx_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spectrumx_visualization_platform_production_postgres
    volumes:
      - spectrumx_visualization_platform_local_postgres_data:/var/lib/postgresql/data
      - spectrumx_visualization_platform_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - spectrumx_network

  redis:
    image: docker.io/redis:6
    container_name: spectrumx_local_redis
    volumes:
      - spectrumx_visualization_platform_local_redis_data:/data
    networks:
      - spectrumx_network

  celeryworker:
    <<: *django
    image: spectrumx_visualization_platform_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    networks:
      - spectrumx_network

  celerybeat:
    <<: *django
    image: spectrumx_visualization_platform_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
    networks:
      - spectrumx_network

  flower:
    <<: *django
    image: spectrumx_visualization_platform_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    networks:
      - spectrumx_network

  jupyter:
    build:
      context: .
      dockerfile: ./compose/local/jupyter/Dockerfile
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=''  # Remove token for testing
    networks:
      - spectrumx_network
    command: "jupyter notebook --allow-root --no-browser --NotebookApp.base_url=/notebooks"

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./compose/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jupyter
    networks:
      - spectrumx_network

networks:
  spectrumx_network:
    driver: bridge
