volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  production_redis_data: {}
  jupyterhub_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: spectrumx_visualization_platform_production_django
    networks:
      - spectrumx_network
    volumes:
      - production_django_media:/app/spectrumx_visualization_platform/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/production/frontend/Dockerfile
    networks:
      - spectrumx_network
    volumes:
      - ./frontend:/app
    depends_on:
      - django

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spectrumx_visualization_platform_production_postgres
    networks:
      - spectrumx_network
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: spectrumx_visualization_platform_production_traefik
    networks:
      - spectrumx_network
    depends_on:
      - django
    volumes:
      - source: ./compose/production/traefik/data/certs
        target: /etc/traefik/certs
        type: bind
        read_only: true
      - source: ./compose/production/traefik/traefik.yml
        target: /etc/traefik/traefik.yml
        type: bind
        read_only: true
      - source: ./compose/production/traefik/credentials.htpasswd
        target: /etc/traefik/dashboard/credentials.htpasswd
        type: bind
        read_only: true
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  # whoami service to test traefik reachability
  # curl --insecure https://whoami.spectrumx.crc.nd.edu
  whoami:
    image: traefik/whoami
    networks:
      - spectrumx_network
    command:
      - --port=2001 # must match port in traefik.yml
      # - --name=sds-01
    # networks:
    #     - sds-network-local

  redis:
    image: docker.io/redis:6
    networks:
      - spectrumx_network
    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: spectrumx_visualization_platform_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: spectrumx_visualization_platform_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: spectrumx_visualization_platform_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: spectrumx_visualization_platform_production_nginx
    networks:
      - spectrumx_network
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro

  jupyter:
    build:
      context: .
      dockerfile: ./compose/production/jupyter/Dockerfile
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - spectrumx_network
    volumes:
      - './compose/production/jupyter/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
      - 'jupyterhub_data:/data'
    group_add:
      - docker
    environment:
      JUPYTERHUB_ADMIN: admin
      DOCKER_NETWORK_NAME: spectrumx_network
      DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
    ports:
      - '8888:8000'
    env_file:
      - ./.envs/.production/.jupyterhub

networks:
  spectrumx_network:
    driver: bridge
    name: spectrumx_network
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
