volumes:
  spectrumx_visualization_platform_local_postgres_data: {}
  spectrumx_visualization_platform_local_postgres_data_backups: {}
  spectrumx_visualization_platform_local_redis_data: {}
  jupyterhub_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: spectrumx_visualization_platform_local_django
    # container_name: spectrumx_visualization_platform_local_django
    depends_on:
      - postgres
      # - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8001:8000"
    command: /start
    networks:
      - sds-network-local

  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/local/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    depends_on:
      - django
      - nginx
    networks:
      - sds-network-local

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spectrumx_visualization_platform_production_postgres
    volumes:
      - spectrumx_visualization_platform_local_postgres_data:/var/lib/postgresql/data
      - spectrumx_visualization_platform_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - sds-network-local

  redis:
    image: docker.io/redis:6
    container_name: spectrumx_local_redis
    volumes:
      - spectrumx_visualization_platform_local_redis_data:/data
    networks:
      - sds-network-local

  celeryworker:
    <<: *django
    image: spectrumx_visualization_platform_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    networks:
      - sds-network-local

  celerybeat:
    <<: *django
    image: spectrumx_visualization_platform_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
    networks:
      - sds-network-local

  flower:
    <<: *django
    image: spectrumx_visualization_platform_local_flower
    ports:
      - "5556:5555"
    command: /start-flower
    networks:
      - sds-network-local

  # jupyter:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/jupyter/Dockerfile
  #     args:
  #       JUPYTERHUB_VERSION: latest
  #   restart: always
  #   image: jupyterhub
  #   container_name: jupyterhub
  #   networks:
  #     sds-network-local:
  #       aliases:
  #         - jupyterhub
  #   volumes:
  #     - './compose/local/jupyter/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro'
  #     - '/var/run/docker.sock:/var/run/docker.sock:rw'
  #     - 'jupyterhub_data:/data'
  #   ports:
  #     - '8888:8000'
  #   env_file:
  #     - ./.envs/.local/.jupyterhub
  #   environment:
  #     JUPYTERHUB_ADMIN: admin
  #     DOCKER_NETWORK_NAME: sds-network-local
  #     DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
  #     DOCKER_NOTEBOOK_DIR: /home/jovyan/work
  #   depends_on:
  #     - nginx

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./compose/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sds-network-local

networks:
  # Use the same network as SDS Gateway
  sds-network-local:
    external: true
