# Generated by Django 4.2.14 on 2025-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sds_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
