# Generated by Django 4.2.14 on 2024-10-24 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SigMFFilePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='spx_vis.file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-data'])])),
                ('meta_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_file', to='spx_vis.file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-meta'])])),
            ],
        ),
    ]
