# Generated by Django 4.2.14 on 2024-10-24 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigmffilepair',
            name='name',
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='data_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-data'])]),
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='meta_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-meta'])]),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
