# Generated by Django 4.2.14 on 2024-11-06 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spx_vis', '0002_remove_sigmffilepair_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('media_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='spx_vis.file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-data'])]),
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='meta_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_file', to='spx_vis.file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sigmf-meta'])]),
        ),
    ]
