# Generated by Django 4.2.14 on 2024-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0003_file_alter_sigmffilepair_data_file_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_filename'),
        ),
    ]
