# Generated by Django 4.2.14 on 2024-11-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0004_file_unique_owner_filename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_owner_filename',
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_filename_for_user'),
        ),
    ]
