# Generated by Django 4.2.14 on 2025-01-13 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spx_vis', '0005_remove_file_unique_owner_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_filename_for_user',
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_capture_filename_for_user'),
        ),
        migrations.AddField(
            model_name='capture',
            name='captureOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='capture',
            constraint=models.UniqueConstraint(fields=('captureOwner', 'name'), name='unique_filename_for_user'),
        ),
    ]
