# Generated by Django 4.2.14 on 2025-01-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0007_rename_name_capture_capturename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capture',
            name='unique_filename_for_user',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_capture_filename_for_user',
        ),
        migrations.RenameField(
            model_name='capture',
            old_name='captureName',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='capture',
            constraint=models.UniqueConstraint(fields=('captureOwner', 'name'), name='unique_capturefilename_for_user'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_filename_for_user'),
        ),
    ]
