# Generated by Django 4.2.14 on 2025-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0008_remove_capture_unique_filename_for_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capture',
            name='unique_capturefilename_for_user',
        ),
        migrations.RenameField(
            model_name='capture',
            old_name='name',
            new_name='capturename',
        ),
        migrations.AddConstraint(
            model_name='capture',
            constraint=models.UniqueConstraint(fields=('captureOwner', 'capturename'), name='unique_capturefilename_for_user'),
        ),
    ]
