# Generated by Django 4.2.14 on 2025-01-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0009_remove_capture_unique_capturefilename_for_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureDatasetIntegrated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_captures', to='spx_vis.capture')),
                ('sigmf_filepair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_captures', to='spx_vis.sigmffilepair')),
            ],
        ),
    ]
