# Generated by Django 4.2.14 on 2025-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0010_capturedatasetintegrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedatasetintegrated',
            name='captureformat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capturedatasetintegrated',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
