# Generated by Django 4.2.14 on 2025-01-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0011_capturedatasetintegrated_captureformat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedatasetintegrated',
            name='sigmf_filepair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_sigmf', to='spx_vis.sigmffilepair'),
        ),
    ]
