# Generated by Django 4.2.14 on 2025-01-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0012_alter_capturedatasetintegrated_sigmf_filepair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedatasetintegrated',
            name='capture',
        ),
    ]
