# Generated by Django 4.2.14 on 2025-01-28 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import spectrumx_visualization_platform.spx_vis.models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0013_remove_capturedatasetintegrated_capture'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capture',
            name='unique_capturefilename_for_user',
        ),
        migrations.RenameField(
            model_name='capture',
            old_name='capturename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='capture',
            old_name='captureOwner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='location',
        ),
        migrations.AddField(
            model_name='capture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='source',
            field=models.CharField(choices=[(spectrumx_visualization_platform.spx_vis.models.CaptureSource['SDS'], 'SDS'), (spectrumx_visualization_platform.spx_vis.models.CaptureSource['SVI_Public'], 'SVI Public'), (spectrumx_visualization_platform.spx_vis.models.CaptureSource['SVI_User'], 'SVI User')], default='svi_user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='type',
            field=models.CharField(choices=[(spectrumx_visualization_platform.spx_vis.models.CaptureType['DigitalRF'], 'Digital RF'), (spectrumx_visualization_platform.spx_vis.models.CaptureType['RadioHound'], 'RadioHound'), (spectrumx_visualization_platform.spx_vis.models.CaptureType['SigMF'], 'SigMF')], default='sigmf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='capture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='spx_vis.capture'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='capturedatasetintegrated',
            name='sigmf_filepair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrated_sigmf', to='spx_vis.sigmffilepair'),
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to='spx_vis.file'),
        ),
        migrations.AlterField(
            model_name='sigmffilepair',
            name='meta_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_file', to='spx_vis.file'),
        ),
        migrations.AddConstraint(
            model_name='capture',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_capturename_for_user'),
        ),
    ]
