# Generated by Django 4.2.14 on 2025-01-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0014_remove_capture_unique_capturefilename_for_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptureDatasetIntegrated',
        ),
    ]
