# Generated by Django 4.2.14 on 2025-01-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0015_delete_capturedatasetintegrated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigMFFilePair',
        ),
    ]
