# Generated by Django 4.2.14 on 2025-02-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0016_delete_sigmffilepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='spx_vis.capture'),
        ),
        migrations.AlterField(
            model_name='file',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
