# Generated by Django 4.2.14 on 2025-03-14 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spectrumx_visualization_platform.spx_vis.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spx_vis', '0017_alter_file_capture_alter_file_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(spectrumx_visualization_platform.spx_vis.models.VisualizationType['Spectrogram'], 'Spectrogram'), (spectrumx_visualization_platform.spx_vis.models.VisualizationType['Waterfall'], 'Waterfall')], max_length=255)),
                ('capture_ids', models.JSONField(help_text='List of capture IDs used in this visualization')),
                ('capture_type', models.CharField(choices=[(spectrumx_visualization_platform.spx_vis.models.CaptureType['DigitalRF'], 'Digital RF'), (spectrumx_visualization_platform.spx_vis.models.CaptureType['RadioHound'], 'RadioHound'), (spectrumx_visualization_platform.spx_vis.models.CaptureType['SigMF'], 'SigMF')], max_length=255)),
                ('capture_source', models.CharField(choices=[(spectrumx_visualization_platform.spx_vis.models.CaptureSource['SDS'], 'SDS'), (spectrumx_visualization_platform.spx_vis.models.CaptureSource['SVI_Public'], 'SVI Public'), (spectrumx_visualization_platform.spx_vis.models.CaptureSource['SVI_User'], 'SVI User')], max_length=255)),
                ('settings', models.JSONField(default=dict, help_text='Type-specific visualization settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
