# Generated by Django 4.2.14 on 2025-04-02 18:41

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Capture = apps.get_model('spx_vis', 'Capture')
    File = apps.get_model('spx_vis', 'File')
    Visualization = apps.get_model('spx_vis', 'Visualization')
    for row in Capture.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    for row in File.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    for row in Visualization.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0019_capture_uuid_file_uuid_visualization_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
