# Generated by Django 4.2.14 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spx_vis', '0021_auto_20250402_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visualization',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visualization',
            name='name',
            field=models.CharField(default='Unsaved Visualization', max_length=255),
            preserve_default=False,
        ),
    ]
